project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
    - text: "Hands On Exercise"
      menu:
      - text: "Hands On Exercise 1"
        href: Hands_On_Exercises/HOE01/HOE_01.html
      - text: "Hands On Exercise 2"
        href: Hands_On_Exercises/HOE02/HOE_02.html
      - text: "Hands On Exercise 3a"
        href: Hands_On_Exercises/HOE03/HOE_03a.html
      - text: "Hands On Exercise 3b"
        href: Hands_On_Exercises/HOE03/HOE_03b.html
      - text: "Hands On Exercise 4a"
        href: Hands_On_Exercises/HOE04/HOE_04a.html
      - text: "Hands On Exercise 4b"
        href: Hands_On_Exercises/HOE04/HOE_04b.html
      - text: "Hands On Exercise 4c"
        href: Hands_On_Exercises/HOE04/HOE_04c.html
      - text: "Hands On Exercise 4d"
        href: Hands_On_Exercises/HOE04/HOE_04d.html
      - text: "Hands On Exercise 5a"
        href: Hands_On_Exercises/HOE05/HOE_05a.html
      - text: "Hands On Exercise 5b"
        href: Hands_On_Exercises/HOE05/HOE_05b.html
      - text: "Hands On Exercise 5c"
        href: Hands_On_Exercises/HOE05/HOE_05c.html
      - text: "Hands On Exercise 5d"
        href: Hands_On_Exercises/HOE05/HOE_05d.html
      - text: "Hands On Exercise 5e"
        href: Hands_On_Exercises/HOE05/HOE_05e.html
      - text: "Hands On Exercise 7"
        href: Hands_On_Exercises/HOE07/HOE_07.html
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1 (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_01/Dashboard1"
      - text: "In-class Exercise 2 (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_02/Dashboard1"
      - text: "In-class Exercise 3 (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_03/Dashboard1"
      - text: "In-class Exercise 4"
        href: In_Class_Exercises/ICE_04/ICE_04.html
      - text: "In-class Exercise 5 (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_05/Dashboard1"
      - text: "In-class Exercise 5"
        href: In_Class_Exercises/ICE_05/ICE_05.html
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take_Home_Exercises/THE_01/THE_01.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

