project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
    - text: "Hands On Exercise"
      menu:
      - text: "Hands On Exercise 1"
        href: Hands_On_Exercises/HOE01/HOE_01.html
      - text: "Hands On Exercise 2"
        href: Hands_On_Exercises/HOE02/HOE_02.html
      - text: "Hands On Exercise 3a"
        href: Hands_On_Exercises/HOE03/HOE_03a.html
      - text: "Hands On Exercise 3b"
        href: Hands_On_Exercises/HOE03/HOE_03b.html
      - text: "Hands On Exercise 4a"
        href: Hands_On_Exercises/HOE04/HOE_04a.html
      - text: "Hands On Exercise 4b"
        href: Hands_On_Exercises/HOE04/HOE_04b.html
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 4"
        href: In_Class_Exercises/ICE_04/ICE_04.html
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take_Home_Exercises/THE_01/THE01.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

