project:
  type: website

website:
  title: "R4VA by Y"
  navbar:
    left:
    - text: "Hands On Exercises"
      menu:
      - text: "1. Introduction to ggplot2"
        href: Hands_On_Exercises/HOE01/HOE_01.html
      - text: "2. Beyond ggplot2 Fundamentals"
        href: Hands_On_Exercises/HOE02/HOE_02.html
      - text: "3.a Interactive Data Visualisations"
        href: Hands_On_Exercises/HOE03/HOE_03a.html
      - text: "3.b Animated Data Visualisations"
        href: Hands_On_Exercises/HOE03/HOE_03b.html
      - text: "4.a Visualising Distribution"
        href: Hands_On_Exercises/HOE04/HOE_04a.html
      - text: "4.b Visual Statistical Analysis"
        href: Hands_On_Exercises/HOE04/HOE_04b.html
      - text: "4.c Visualising Uncertainty"
        href: Hands_On_Exercises/HOE04/HOE_04c.html
      - text: "4.d Funnel Plots"
        href: Hands_On_Exercises/HOE04/HOE_04d.html
      - text: "5.a Visual Correlation Analysis"
        href: Hands_On_Exercises/HOE05/HOE_05a.html
      - text: "5.b Multivariate Data with Ternary Plots"
        href: Hands_On_Exercises/HOE05/HOE_05b.html
      - text: "5.c Multivariate Data with Heatmaps"
        href: Hands_On_Exercises/HOE05/HOE_05c.html
      - text: "5.d Multivariate Data with Parallel Coordinates Plot"
        href: Hands_On_Exercises/HOE05/HOE_05d.html
      - text: "5.e Treemaps"
        href: Hands_On_Exercises/HOE05/HOE_05e.html
      - text: "7 Time Oriented Data"
        href: Hands_On_Exercises/HOE07/HOE_07.html
      - text: "8.a Choropleth Mapping"
        href: Hands_On_Exercises/HOE08/HOE_08a.html
      - text: "8.b Visualising Geospatial Point Data"
        href: Hands_On_Exercises/HOE08/HOE_08b.html
      - text: "8.c Analytical Mapping"
        href: Hands_On_Exercises/HOE08/HOE_08c.html
      - text: "9. Visualising Network Data"
        href: Hands_On_Exercises/HOE09/HOE_09.html
      - text: "10. Information Dashboard Design"
        href: Hands_On_Exercises/HOE10/HOE_10.html
    - text: "In-class Exercises"
      menu:
      - text: "1 Introduction to Tableau (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_01/Dashboard1"
      - text: "2 Beyond Tableau Basics and Bubble Plots (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_02/Dashboard1"
      - text: "3 Applying Filters Across Worksheets (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_03/Dashboard1"
      - text: "4 Boxplot"
        href: In_Class_Exercises/ICE_04/ICE_04.html
      - text: "5.a Treemaps (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_05/Dashboard1"
      - text: "5.b Model Building and Summarising"
        href: In_Class_Exercises/ICE_05/ICE_05.html
      - text: "6. Introduction to Shiny (Shiny)"
        href: "https://yisbetterthanx.shinyapps.io/In_Class_Exercise_06_Introduction_to_Shiny/"
      - text: "7. Time-Series Modelling"
        href: In_Class_Exercises/ICE_07/ICE_07.html
      - text: "8.a Geospatial Lottery Data (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_08/SingaporePoolsNumberofWinningsbyShopType"
      - text: "8.b Geospatial Property Transactions (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_08_2/AnimatedandInteractiveGeospatialPropertyTransactions"
      - text: "10  Bullet Plot and Sparklines (Tableau)"
        href: "https://public.tableau.com/app/profile/junyit.yee/viz/InClassExercise_10/CoffeeChainSalesReportbyProductandProductType"
    - text: "Take-home Exercises"
      menu:
      - text: "1. Modelling of Simulated Shipping Data"
        href: Take_Home_Exercises/THE_01/THE_01.html
      - text: "2. Singapore's Balance of Trade"
        href: Take_Home_Exercises/THE_02/THE_02.html
      - text: "3. Prototype for Shiny of GeBIZ Data"
        href: Take_Home_Exercises/THE_03/THE_03.html
    - text: "Group Project"
      href: "https://isss608ay2425s2-g3.netlify.app/"
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

